### ISSUE TITLE
License

### ISSUE THREAD

**Issue by laurmaedje** [pdf-rs/font#5]
Hey,

I would like to depend on this project transitively through [grafeia/ReX](https://github.com/grafeia/ReX) as it can work with arbitrary font files in contrast to the original ReX.

However, this project as well [unicode-math](https://github.com/s3bk/unicode-math) unfortunately don't have license files. In case you would like for this project to be permissively accessible, it would be very kind if you could add license files!

**Comment by s3bk** [comment]
looks like unicode-math has https://www.latex-project.org/lppl/
I don't care about what license font gets.

**Comment by laurmaedje** [comment]
Thanks for the quick response! The LPPL part applies to the `.tex` file but the Rust files are currently covered by no license. If you don't care, I guess MIT License would be a good fit. I could make two PRs or you could just push them.

**Comment by s3bk** [comment]
Added MIT to unicode-math, font and encoding.
https://github.com/pdf-rs/encoding/tree/master contains AGLFN stuff.. no idea what that means for you.

**Comment by s3bk** [comment]
If you need font metrics, you also need the standard fonts which is a much worse problem.

**Comment by laurmaedje** [comment]
Thank you very much! The AGLFN stuff seems fine, it's under BSD-3 clause.
